### PR TITLE
Adds i2c bus

### PR DESCRIPTION
**Pull request by gambrose**
I used `i2c::WriteRead` and `i2c::Write` traits from i2c. I could simplify it to just use `i2c::WriteRead` to also write with.

For `I2cBus::new` and `I2cBus::free` I didn't define the trail constraints as you did for the SpiBus. Being a rust newbie, I'm not really sure why you did that and it seems to work fine without so I left it out.

I have tested it on BMP280 using a raspberry pi pico. This seems to work as I am getting values back and not errors but still need to calculate the altitude from these to confirm it's OK.

### CODE REVIEW

**Comment by gambrose** [comment]
I must have done something wrong somewhere as I am getting pressures above the pressure at sea level (101325 Pa) and I am not below the sea.

This is how I am reading out the value;
```rust
let mut bmp = BMP280::new(I2cBus::new(i2c, I2cAddress::SdoToGnd));

let calibration = bmp.read_calibration().unwrap();

bmp.set_pressure_oversampling(PressureOversampling::UltraHighResolution).unwrap();
bmp.set_temperature_oversampling(TemperatureOversampling::LowPower).unwrap();
bmp.set_mode(Mode::Normal).unwrap();

let (pres_raw, temp_raw) = bmp.read_measurements().unwrap();
let temp = temp_raw.t_fine(&calibration);
let pres = pres_raw.i64_compensated(temp, &calibration);
```

**Comment by qiuchengxuan** [comment]
Perhaps you'd like to update version either since I'm going to publish a new version

**Comment by qiuchengxuan** [comment]
> I must have done something wrong somewhere as I am getting pressures above the pressure at sea level (101325 Pa) and I am not below the sea.
> 
> This is how I am reading out the value;
> 
> ```rust
> let mut bmp = BMP280::new(I2cBus::new(i2c, I2cAddress::SdoToGnd));
> 
> let calibration = bmp.read_calibration().unwrap();
> 
> bmp.set_pressure_oversampling(PressureOversampling::UltraHighResolution).unwrap();
> bmp.set_temperature_oversampling(TemperatureOversampling::LowPower).unwrap();
> bmp.set_mode(Mode::Normal).unwrap();
> 
> let (pres_raw, temp_raw) = bmp.read_measurements().unwrap();
> let temp = temp_raw.t_fine(&calibration);
> let pres = pres_raw.i64_compensated(temp, &calibration);
> ```

I'm not that familiar to barometer either, but if you read out calibration value correctly, you did it right.
Barometer readout could be affected by several factors, including temperature and humidity. So if not too much error compared to your local pressure, I don't think you did something wrong, perhaps you should not use sea level pressure as reference, and open area other than indoors could be more accurate.

**Comment by qiuchengxuan** [comment]
> I must have done something wrong somewhere as I am getting pressures above the pressure at sea level (101325 Pa) and I am not below the sea.
> 
> This is how I am reading out the value;
> 
> ```rust
> let mut bmp = BMP280::new(I2cBus::new(i2c, I2cAddress::SdoToGnd));
> 
> let calibration = bmp.read_calibration().unwrap();
> 
> bmp.set_pressure_oversampling(PressureOversampling::UltraHighResolution).unwrap();
> bmp.set_temperature_oversampling(TemperatureOversampling::LowPower).unwrap();
> bmp.set_mode(Mode::Normal).unwrap();
> 
> let (pres_raw, temp_raw) = bmp.read_measurements().unwrap();
> let temp = temp_raw.t_fine(&calibration);
> let pres = pres_raw.i64_compensated(temp, &calibration);
> ```

I'm using following code to use BMP280
```rust
        self.set_pressure_oversampling(PressureOversampling::StandardResolution)?;
        self.set_temperature_oversampling(TemperatureOversampling::UltraLowPower)?;
        self.set_mode(Mode::Normal)?;
        self.set_standby_time(StandbyTime::Hertz16)?;
        self.set_iir_filter(8)
...
pub struct Compensator(pub Calibration);
                                                                                                                                               
impl Compensator {
    pub fn convert(&self, bytes: &[u8]) -> Pressure {
        let raw_pressure = RawPressure::from_bytes(&bytes[2..]);
        let t_fine = RawTemperature::from_bytes(&bytes[5..]).t_fine(&self.0);
        Pressure(raw_pressure.compensated(t_fine, &self.0))
    }
}
...
let compensator = Compensator(bmp280.read_calibration().unwrap_or_default());
```

**Comment by qiuchengxuan** [comment]
> I used `i2c::WriteRead` and `i2c::Write` traits from i2c. I could simplify it to just use `i2c::WriteRead` to also write with.
> 
> For `I2cBus::new` and `I2cBus::free` I didn't define the trail constraints as you did for the SpiBus. Being a rust newbie, I'm not really sure why you did that and it seems to work fine without so I left it out.
> 
> I have tested it on BMP280 using a raspberry pi pico. This seems to work as I am getting values back and not errors but still need to calculate the altitude from these to confirm it's OK.

The only difference between whether define trait bounds for new and free is where compile error occur when trait bounds not satisfied, so both are ok.

**Comment by gambrose** [comment]
In an effort to try and understand the strange results I'm getting, I have put together a test based on the example on page 23 of the [data sheet](https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmp280-ds001.pdf)

It wasn't clear where the data for the existing test case came from.

This does not pass as the convert from raw temp to t_fine is returning the wrong results. I am fairly sure I have made a mistake putting this test together but I cannot work out what it is.

```rust
#[test]
fn compensate_temp_example_in_data_sheet() {
    use super::{Calibration, RawTemperature};

    let calibration_bytes = hex!(
        "70 6B 43 67 18 FC 00 00 00 00 00 00
        00 00 00 00 00 00 00 00 00 00 00 00"
    );
    let calibration = Calibration::from_bytes(&calibration_bytes);

    assert_eq!(27504, calibration.dig_t(1));
    assert_eq!(26435, calibration.dig_t(2));
    assert_eq!(-1000, calibration.dig_t(3));

    let raw_temperature = RawTemperature::from_bytes(&hex!("65 5A 0C"));

    assert_eq!(415148, raw_temperature.0);

    let t_fine = raw_temperature.t_fine(&calibration);

    assert_eq!(128422, t_fine.0);

    assert_eq!(2508, t_fine.degree_celsuis_x100());
}
```

**Comment by qiuchengxuan** [comment]
> 

Your raw temperature is incorrect, it should be `assert_eq!(519888, raw_temperature.0);` according to datasheet

**Comment by gambrose** [comment]
That's interesting, the 519888 value does make it pass. But the example lists 519888 as registers 0xF7 / 0xF8 / 0xF9[7:4] which are the pressure register not the temp register.

Thanks for the help btw.

**Comment by gambrose** [comment]
I have updated the version to 0.2.0 as this is a new feature.

Seems to be working fairly well for me now.

**Pull request merged**
